/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as AppRouteImport } from './app/app'
import { Route as AdminRouteImport } from './app/admin'
import { Route as MarketingRouteImport } from './app/_marketing'
import { Route as AppIndexRouteImport } from './app/app/index'
import { Route as AdminIndexRouteImport } from './app/admin/index'
import { Route as MarketingIndexRouteImport } from './app/_marketing/index'
import { Route as AppSettingsRouteImport } from './app/app/settings'
import { Route as AppNotificationsRouteImport } from './app/app/notifications'
import { Route as AppLoginRouteImport } from './app/app/login'
import { Route as AppImagesRouteImport } from './app/app/images'
import { Route as AppEventsRouteImport } from './app/app/events'
import { Route as ApiAppleAppSiteAssociationRouteImport } from './app/api/apple-app-site-association'
import { Route as AdminLoginRouteImport } from './app/admin/login'
import { Route as AdminDashboardRouteImport } from './app/admin/dashboard'
import { Route as MarketingTermsOfServiceRouteImport } from './app/_marketing/terms-of-service'
import { Route as MarketingPrivacyPolicyRouteImport } from './app/_marketing/privacy-policy'
import { Route as MarketingDeleteAccountRouteImport } from './app/_marketing/delete-account'
import { Route as AdminDashboardIndexRouteImport } from './app/admin/dashboard/index'
import { Route as AppPaymentsReturnRouteImport } from './app/app/payments.return'
import { Route as AppEventsNewRouteImport } from './app/app/events.new'
import { Route as AppEventsEventIdRouteImport } from './app/app/events.$eventId'
import { Route as ApiWellKnownAssetlinksRouteImport } from './app/api/well-known.assetlinks'
import { Route as ApiWellKnownAppleAppSiteAssociationRouteImport } from './app/api/well-known.apple-app-site-association'
import { Route as AdminDashboardUsersRouteImport } from './app/admin/dashboard/users'
import { Route as AdminDashboardTicketsRouteImport } from './app/admin/dashboard/tickets'
import { Route as AdminDashboardSettingsRouteImport } from './app/admin/dashboard/settings'
import { Route as AdminDashboardPaymentsRouteImport } from './app/admin/dashboard/payments'
import { Route as AdminDashboardNotificationsRouteImport } from './app/admin/dashboard/notifications'
import { Route as AdminDashboardMediaRouteImport } from './app/admin/dashboard/media'
import { Route as AdminDashboardEventsRouteImport } from './app/admin/dashboard/events'
import { Route as AdminDashboardAuditLogRouteImport } from './app/admin/dashboard/audit-log'
import { Route as MarketingPaymentsReturnRouteImport } from './app/_marketing/payments.return'
import { Route as MarketingJoinInviteIdRouteImport } from './app/_marketing/join.$inviteId'
import { Route as AppEventsInvitationsAcceptRouteImport } from './app/app/events.invitations.accept'
import { Route as AdminDashboardUsersUserIdRouteImport } from './app/admin/dashboard/users.$userId'
import { Route as AdminDashboardTicketsTicketIdRouteImport } from './app/admin/dashboard/tickets.$ticketId'
import { Route as AdminDashboardEventsEventIdRouteImport } from './app/admin/dashboard/events.$eventId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppImagesRoute = AppImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const ApiAppleAppSiteAssociationRoute =
  ApiAppleAppSiteAssociationRouteImport.update({
    id: '/api/apple-app-site-association',
    path: '/api/apple-app-site-association',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const MarketingTermsOfServiceRoute = MarketingTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPrivacyPolicyRoute = MarketingPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingDeleteAccountRoute = MarketingDeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => MarketingRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AppPaymentsReturnRoute = AppPaymentsReturnRouteImport.update({
  id: '/payments/return',
  path: '/payments/return',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsNewRoute = AppEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppEventsRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AppEventsRoute,
} as any)
const ApiWellKnownAssetlinksRoute = ApiWellKnownAssetlinksRouteImport.update({
  id: '/api/well-known/assetlinks',
  path: '/api/well-known/assetlinks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWellKnownAppleAppSiteAssociationRoute =
  ApiWellKnownAppleAppSiteAssociationRouteImport.update({
    id: '/api/well-known/apple-app-site-association',
    path: '/api/well-known/apple-app-site-association',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardUsersRoute = AdminDashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardTicketsRoute = AdminDashboardTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardSettingsRoute = AdminDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardPaymentsRoute = AdminDashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardNotificationsRoute =
  AdminDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardMediaRoute = AdminDashboardMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardEventsRoute = AdminDashboardEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardAuditLogRoute = AdminDashboardAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const MarketingPaymentsReturnRoute = MarketingPaymentsReturnRouteImport.update({
  id: '/payments/return',
  path: '/payments/return',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingJoinInviteIdRoute = MarketingJoinInviteIdRouteImport.update({
  id: '/join/$inviteId',
  path: '/join/$inviteId',
  getParentRoute: () => MarketingRoute,
} as any)
const AppEventsInvitationsAcceptRoute =
  AppEventsInvitationsAcceptRouteImport.update({
    id: '/invitations/accept',
    path: '/invitations/accept',
    getParentRoute: () => AppEventsRoute,
  } as any)
const AdminDashboardUsersUserIdRoute =
  AdminDashboardUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AdminDashboardUsersRoute,
  } as any)
const AdminDashboardTicketsTicketIdRoute =
  AdminDashboardTicketsTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => AdminDashboardTicketsRoute,
  } as any)
const AdminDashboardEventsEventIdRoute =
  AdminDashboardEventsEventIdRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => AdminDashboardEventsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/delete-account': typeof MarketingDeleteAccountRoute
  '/privacy-policy': typeof MarketingPrivacyPolicyRoute
  '/terms-of-service': typeof MarketingTermsOfServiceRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/api/apple-app-site-association': typeof ApiAppleAppSiteAssociationRoute
  '/app/events': typeof AppEventsRouteWithChildren
  '/app/images': typeof AppImagesRoute
  '/app/login': typeof AppLoginRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/join/$inviteId': typeof MarketingJoinInviteIdRoute
  '/payments/return': typeof MarketingPaymentsReturnRoute
  '/admin/dashboard/audit-log': typeof AdminDashboardAuditLogRoute
  '/admin/dashboard/events': typeof AdminDashboardEventsRouteWithChildren
  '/admin/dashboard/media': typeof AdminDashboardMediaRoute
  '/admin/dashboard/notifications': typeof AdminDashboardNotificationsRoute
  '/admin/dashboard/payments': typeof AdminDashboardPaymentsRoute
  '/admin/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/admin/dashboard/tickets': typeof AdminDashboardTicketsRouteWithChildren
  '/admin/dashboard/users': typeof AdminDashboardUsersRouteWithChildren
  '/api/well-known/apple-app-site-association': typeof ApiWellKnownAppleAppSiteAssociationRoute
  '/api/well-known/assetlinks': typeof ApiWellKnownAssetlinksRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/events/new': typeof AppEventsNewRoute
  '/app/payments/return': typeof AppPaymentsReturnRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/dashboard/events/$eventId': typeof AdminDashboardEventsEventIdRoute
  '/admin/dashboard/tickets/$ticketId': typeof AdminDashboardTicketsTicketIdRoute
  '/admin/dashboard/users/$userId': typeof AdminDashboardUsersUserIdRoute
  '/app/events/invitations/accept': typeof AppEventsInvitationsAcceptRoute
}
export interface FileRoutesByTo {
  '/delete-account': typeof MarketingDeleteAccountRoute
  '/privacy-policy': typeof MarketingPrivacyPolicyRoute
  '/terms-of-service': typeof MarketingTermsOfServiceRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/apple-app-site-association': typeof ApiAppleAppSiteAssociationRoute
  '/app/events': typeof AppEventsRouteWithChildren
  '/app/images': typeof AppImagesRoute
  '/app/login': typeof AppLoginRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/': typeof MarketingIndexRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/join/$inviteId': typeof MarketingJoinInviteIdRoute
  '/payments/return': typeof MarketingPaymentsReturnRoute
  '/admin/dashboard/audit-log': typeof AdminDashboardAuditLogRoute
  '/admin/dashboard/events': typeof AdminDashboardEventsRouteWithChildren
  '/admin/dashboard/media': typeof AdminDashboardMediaRoute
  '/admin/dashboard/notifications': typeof AdminDashboardNotificationsRoute
  '/admin/dashboard/payments': typeof AdminDashboardPaymentsRoute
  '/admin/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/admin/dashboard/tickets': typeof AdminDashboardTicketsRouteWithChildren
  '/admin/dashboard/users': typeof AdminDashboardUsersRouteWithChildren
  '/api/well-known/apple-app-site-association': typeof ApiWellKnownAppleAppSiteAssociationRoute
  '/api/well-known/assetlinks': typeof ApiWellKnownAssetlinksRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/events/new': typeof AppEventsNewRoute
  '/app/payments/return': typeof AppPaymentsReturnRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/dashboard/events/$eventId': typeof AdminDashboardEventsEventIdRoute
  '/admin/dashboard/tickets/$ticketId': typeof AdminDashboardTicketsTicketIdRoute
  '/admin/dashboard/users/$userId': typeof AdminDashboardUsersUserIdRoute
  '/app/events/invitations/accept': typeof AppEventsInvitationsAcceptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/_marketing/delete-account': typeof MarketingDeleteAccountRoute
  '/_marketing/privacy-policy': typeof MarketingPrivacyPolicyRoute
  '/_marketing/terms-of-service': typeof MarketingTermsOfServiceRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/api/apple-app-site-association': typeof ApiAppleAppSiteAssociationRoute
  '/app/events': typeof AppEventsRouteWithChildren
  '/app/images': typeof AppImagesRoute
  '/app/login': typeof AppLoginRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/_marketing/join/$inviteId': typeof MarketingJoinInviteIdRoute
  '/_marketing/payments/return': typeof MarketingPaymentsReturnRoute
  '/admin/dashboard/audit-log': typeof AdminDashboardAuditLogRoute
  '/admin/dashboard/events': typeof AdminDashboardEventsRouteWithChildren
  '/admin/dashboard/media': typeof AdminDashboardMediaRoute
  '/admin/dashboard/notifications': typeof AdminDashboardNotificationsRoute
  '/admin/dashboard/payments': typeof AdminDashboardPaymentsRoute
  '/admin/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/admin/dashboard/tickets': typeof AdminDashboardTicketsRouteWithChildren
  '/admin/dashboard/users': typeof AdminDashboardUsersRouteWithChildren
  '/api/well-known/apple-app-site-association': typeof ApiWellKnownAppleAppSiteAssociationRoute
  '/api/well-known/assetlinks': typeof ApiWellKnownAssetlinksRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/events/new': typeof AppEventsNewRoute
  '/app/payments/return': typeof AppPaymentsReturnRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/dashboard/events/$eventId': typeof AdminDashboardEventsEventIdRoute
  '/admin/dashboard/tickets/$ticketId': typeof AdminDashboardTicketsTicketIdRoute
  '/admin/dashboard/users/$userId': typeof AdminDashboardUsersUserIdRoute
  '/app/events/invitations/accept': typeof AppEventsInvitationsAcceptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/delete-account'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/admin/dashboard'
    | '/admin/login'
    | '/api/apple-app-site-association'
    | '/app/events'
    | '/app/images'
    | '/app/login'
    | '/app/notifications'
    | '/app/settings'
    | '/admin/'
    | '/app/'
    | '/join/$inviteId'
    | '/payments/return'
    | '/admin/dashboard/audit-log'
    | '/admin/dashboard/events'
    | '/admin/dashboard/media'
    | '/admin/dashboard/notifications'
    | '/admin/dashboard/payments'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/tickets'
    | '/admin/dashboard/users'
    | '/api/well-known/apple-app-site-association'
    | '/api/well-known/assetlinks'
    | '/app/events/$eventId'
    | '/app/events/new'
    | '/app/payments/return'
    | '/admin/dashboard/'
    | '/admin/dashboard/events/$eventId'
    | '/admin/dashboard/tickets/$ticketId'
    | '/admin/dashboard/users/$userId'
    | '/app/events/invitations/accept'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/delete-account'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/admin/login'
    | '/api/apple-app-site-association'
    | '/app/events'
    | '/app/images'
    | '/app/login'
    | '/app/notifications'
    | '/app/settings'
    | '/'
    | '/admin'
    | '/app'
    | '/join/$inviteId'
    | '/payments/return'
    | '/admin/dashboard/audit-log'
    | '/admin/dashboard/events'
    | '/admin/dashboard/media'
    | '/admin/dashboard/notifications'
    | '/admin/dashboard/payments'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/tickets'
    | '/admin/dashboard/users'
    | '/api/well-known/apple-app-site-association'
    | '/api/well-known/assetlinks'
    | '/app/events/$eventId'
    | '/app/events/new'
    | '/app/payments/return'
    | '/admin/dashboard'
    | '/admin/dashboard/events/$eventId'
    | '/admin/dashboard/tickets/$ticketId'
    | '/admin/dashboard/users/$userId'
    | '/app/events/invitations/accept'
  id:
    | '__root__'
    | '/_marketing'
    | '/admin'
    | '/app'
    | '/_marketing/delete-account'
    | '/_marketing/privacy-policy'
    | '/_marketing/terms-of-service'
    | '/admin/dashboard'
    | '/admin/login'
    | '/api/apple-app-site-association'
    | '/app/events'
    | '/app/images'
    | '/app/login'
    | '/app/notifications'
    | '/app/settings'
    | '/_marketing/'
    | '/admin/'
    | '/app/'
    | '/_marketing/join/$inviteId'
    | '/_marketing/payments/return'
    | '/admin/dashboard/audit-log'
    | '/admin/dashboard/events'
    | '/admin/dashboard/media'
    | '/admin/dashboard/notifications'
    | '/admin/dashboard/payments'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/tickets'
    | '/admin/dashboard/users'
    | '/api/well-known/apple-app-site-association'
    | '/api/well-known/assetlinks'
    | '/app/events/$eventId'
    | '/app/events/new'
    | '/app/payments/return'
    | '/admin/dashboard/'
    | '/admin/dashboard/events/$eventId'
    | '/admin/dashboard/tickets/$ticketId'
    | '/admin/dashboard/users/$userId'
    | '/app/events/invitations/accept'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ApiAppleAppSiteAssociationRoute: typeof ApiAppleAppSiteAssociationRoute
  ApiWellKnownAppleAppSiteAssociationRoute: typeof ApiWellKnownAppleAppSiteAssociationRoute
  ApiWellKnownAssetlinksRoute: typeof ApiWellKnownAssetlinksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/images': {
      id: '/app/images'
      path: '/images'
      fullPath: '/app/images'
      preLoaderRoute: typeof AppImagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events': {
      id: '/app/events'
      path: '/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/apple-app-site-association': {
      id: '/api/apple-app-site-association'
      path: '/api/apple-app-site-association'
      fullPath: '/api/apple-app-site-association'
      preLoaderRoute: typeof ApiAppleAppSiteAssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_marketing/terms-of-service': {
      id: '/_marketing/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof MarketingTermsOfServiceRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/privacy-policy': {
      id: '/_marketing/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof MarketingPrivacyPolicyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/delete-account': {
      id: '/_marketing/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof MarketingDeleteAccountRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/app/payments/return': {
      id: '/app/payments/return'
      path: '/payments/return'
      fullPath: '/app/payments/return'
      preLoaderRoute: typeof AppPaymentsReturnRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events/new': {
      id: '/app/events/new'
      path: '/new'
      fullPath: '/app/events/new'
      preLoaderRoute: typeof AppEventsNewRouteImport
      parentRoute: typeof AppEventsRoute
    }
    '/app/events/$eventId': {
      id: '/app/events/$eventId'
      path: '/$eventId'
      fullPath: '/app/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppEventsRoute
    }
    '/api/well-known/assetlinks': {
      id: '/api/well-known/assetlinks'
      path: '/api/well-known/assetlinks'
      fullPath: '/api/well-known/assetlinks'
      preLoaderRoute: typeof ApiWellKnownAssetlinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/well-known/apple-app-site-association': {
      id: '/api/well-known/apple-app-site-association'
      path: '/api/well-known/apple-app-site-association'
      fullPath: '/api/well-known/apple-app-site-association'
      preLoaderRoute: typeof ApiWellKnownAppleAppSiteAssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/users': {
      id: '/admin/dashboard/users'
      path: '/users'
      fullPath: '/admin/dashboard/users'
      preLoaderRoute: typeof AdminDashboardUsersRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/tickets': {
      id: '/admin/dashboard/tickets'
      path: '/tickets'
      fullPath: '/admin/dashboard/tickets'
      preLoaderRoute: typeof AdminDashboardTicketsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/settings': {
      id: '/admin/dashboard/settings'
      path: '/settings'
      fullPath: '/admin/dashboard/settings'
      preLoaderRoute: typeof AdminDashboardSettingsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/payments': {
      id: '/admin/dashboard/payments'
      path: '/payments'
      fullPath: '/admin/dashboard/payments'
      preLoaderRoute: typeof AdminDashboardPaymentsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/notifications': {
      id: '/admin/dashboard/notifications'
      path: '/notifications'
      fullPath: '/admin/dashboard/notifications'
      preLoaderRoute: typeof AdminDashboardNotificationsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/media': {
      id: '/admin/dashboard/media'
      path: '/media'
      fullPath: '/admin/dashboard/media'
      preLoaderRoute: typeof AdminDashboardMediaRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/events': {
      id: '/admin/dashboard/events'
      path: '/events'
      fullPath: '/admin/dashboard/events'
      preLoaderRoute: typeof AdminDashboardEventsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/audit-log': {
      id: '/admin/dashboard/audit-log'
      path: '/audit-log'
      fullPath: '/admin/dashboard/audit-log'
      preLoaderRoute: typeof AdminDashboardAuditLogRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/_marketing/payments/return': {
      id: '/_marketing/payments/return'
      path: '/payments/return'
      fullPath: '/payments/return'
      preLoaderRoute: typeof MarketingPaymentsReturnRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/join/$inviteId': {
      id: '/_marketing/join/$inviteId'
      path: '/join/$inviteId'
      fullPath: '/join/$inviteId'
      preLoaderRoute: typeof MarketingJoinInviteIdRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/app/events/invitations/accept': {
      id: '/app/events/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/app/events/invitations/accept'
      preLoaderRoute: typeof AppEventsInvitationsAcceptRouteImport
      parentRoute: typeof AppEventsRoute
    }
    '/admin/dashboard/users/$userId': {
      id: '/admin/dashboard/users/$userId'
      path: '/$userId'
      fullPath: '/admin/dashboard/users/$userId'
      preLoaderRoute: typeof AdminDashboardUsersUserIdRouteImport
      parentRoute: typeof AdminDashboardUsersRoute
    }
    '/admin/dashboard/tickets/$ticketId': {
      id: '/admin/dashboard/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/admin/dashboard/tickets/$ticketId'
      preLoaderRoute: typeof AdminDashboardTicketsTicketIdRouteImport
      parentRoute: typeof AdminDashboardTicketsRoute
    }
    '/admin/dashboard/events/$eventId': {
      id: '/admin/dashboard/events/$eventId'
      path: '/$eventId'
      fullPath: '/admin/dashboard/events/$eventId'
      preLoaderRoute: typeof AdminDashboardEventsEventIdRouteImport
      parentRoute: typeof AdminDashboardEventsRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingDeleteAccountRoute: typeof MarketingDeleteAccountRoute
  MarketingPrivacyPolicyRoute: typeof MarketingPrivacyPolicyRoute
  MarketingTermsOfServiceRoute: typeof MarketingTermsOfServiceRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingJoinInviteIdRoute: typeof MarketingJoinInviteIdRoute
  MarketingPaymentsReturnRoute: typeof MarketingPaymentsReturnRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingDeleteAccountRoute: MarketingDeleteAccountRoute,
  MarketingPrivacyPolicyRoute: MarketingPrivacyPolicyRoute,
  MarketingTermsOfServiceRoute: MarketingTermsOfServiceRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingJoinInviteIdRoute: MarketingJoinInviteIdRoute,
  MarketingPaymentsReturnRoute: MarketingPaymentsReturnRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface AdminDashboardEventsRouteChildren {
  AdminDashboardEventsEventIdRoute: typeof AdminDashboardEventsEventIdRoute
}

const AdminDashboardEventsRouteChildren: AdminDashboardEventsRouteChildren = {
  AdminDashboardEventsEventIdRoute: AdminDashboardEventsEventIdRoute,
}

const AdminDashboardEventsRouteWithChildren =
  AdminDashboardEventsRoute._addFileChildren(AdminDashboardEventsRouteChildren)

interface AdminDashboardTicketsRouteChildren {
  AdminDashboardTicketsTicketIdRoute: typeof AdminDashboardTicketsTicketIdRoute
}

const AdminDashboardTicketsRouteChildren: AdminDashboardTicketsRouteChildren = {
  AdminDashboardTicketsTicketIdRoute: AdminDashboardTicketsTicketIdRoute,
}

const AdminDashboardTicketsRouteWithChildren =
  AdminDashboardTicketsRoute._addFileChildren(
    AdminDashboardTicketsRouteChildren,
  )

interface AdminDashboardUsersRouteChildren {
  AdminDashboardUsersUserIdRoute: typeof AdminDashboardUsersUserIdRoute
}

const AdminDashboardUsersRouteChildren: AdminDashboardUsersRouteChildren = {
  AdminDashboardUsersUserIdRoute: AdminDashboardUsersUserIdRoute,
}

const AdminDashboardUsersRouteWithChildren =
  AdminDashboardUsersRoute._addFileChildren(AdminDashboardUsersRouteChildren)

interface AdminDashboardRouteChildren {
  AdminDashboardAuditLogRoute: typeof AdminDashboardAuditLogRoute
  AdminDashboardEventsRoute: typeof AdminDashboardEventsRouteWithChildren
  AdminDashboardMediaRoute: typeof AdminDashboardMediaRoute
  AdminDashboardNotificationsRoute: typeof AdminDashboardNotificationsRoute
  AdminDashboardPaymentsRoute: typeof AdminDashboardPaymentsRoute
  AdminDashboardSettingsRoute: typeof AdminDashboardSettingsRoute
  AdminDashboardTicketsRoute: typeof AdminDashboardTicketsRouteWithChildren
  AdminDashboardUsersRoute: typeof AdminDashboardUsersRouteWithChildren
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardAuditLogRoute: AdminDashboardAuditLogRoute,
  AdminDashboardEventsRoute: AdminDashboardEventsRouteWithChildren,
  AdminDashboardMediaRoute: AdminDashboardMediaRoute,
  AdminDashboardNotificationsRoute: AdminDashboardNotificationsRoute,
  AdminDashboardPaymentsRoute: AdminDashboardPaymentsRoute,
  AdminDashboardSettingsRoute: AdminDashboardSettingsRoute,
  AdminDashboardTicketsRoute: AdminDashboardTicketsRouteWithChildren,
  AdminDashboardUsersRoute: AdminDashboardUsersRouteWithChildren,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppEventsRouteChildren {
  AppEventsEventIdRoute: typeof AppEventsEventIdRoute
  AppEventsNewRoute: typeof AppEventsNewRoute
  AppEventsInvitationsAcceptRoute: typeof AppEventsInvitationsAcceptRoute
}

const AppEventsRouteChildren: AppEventsRouteChildren = {
  AppEventsEventIdRoute: AppEventsEventIdRoute,
  AppEventsNewRoute: AppEventsNewRoute,
  AppEventsInvitationsAcceptRoute: AppEventsInvitationsAcceptRoute,
}

const AppEventsRouteWithChildren = AppEventsRoute._addFileChildren(
  AppEventsRouteChildren,
)

interface AppRouteChildren {
  AppEventsRoute: typeof AppEventsRouteWithChildren
  AppImagesRoute: typeof AppImagesRoute
  AppLoginRoute: typeof AppLoginRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPaymentsReturnRoute: typeof AppPaymentsReturnRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEventsRoute: AppEventsRouteWithChildren,
  AppImagesRoute: AppImagesRoute,
  AppLoginRoute: AppLoginRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppPaymentsReturnRoute: AppPaymentsReturnRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ApiAppleAppSiteAssociationRoute: ApiAppleAppSiteAssociationRoute,
  ApiWellKnownAppleAppSiteAssociationRoute:
    ApiWellKnownAppleAppSiteAssociationRoute,
  ApiWellKnownAssetlinksRoute: ApiWellKnownAssetlinksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
